// API endpoint "/virtualcards/{id}/transactions" is not returning any transactions on the guest card
// manually getting the transactionID from the webpage and getting the info from 
// "transactions/{transactionID}" endpoint

const txn1 = {
    "id": "txn_6TFInvo4zvn8cN4MyoTPKv",
    "cardholderId": "u_4ghf9XE19xkAF0SFuvESez",
    "cardholderName": "Sarah Sanzari",
    "cardholderEmail": "sarah@paywithextend.com",
    "recipientName": "Tan Nguyen",
    "recipientEmail": "nt7nguye@uwaterloo.ca",
    "recipientId": "u_4oKYQdyC0vV9H3vshB133z",
    "nameOnCard": "Tan Nguyen",
    "source": "VIRTUAL",
    "receiptRequired": false,
    "vcnLast4": "4061",
    "vcnDisplayName": "Tan’s take home assignment",
    "virtualCardId": "vc_17Z9YOuZ1drA6jMwZ4ys4E",
    "type": "DEBIT",
    "status": "CLEARED",
    "approvalCode": "365152",
    "authBillingAmountCents": 1879,
    "authBillingCurrency": "USD",
    "authMerchantAmountCents": 1879,
    "authMerchantCurrency": "USD",
    "authExchangeRate": 1.0,
    "clearingBillingAmountCents": 1900,
    "clearingBillingCurrency": "USD",
    "clearingMerchantAmountCents": 1900,
    "clearingMerchantCurrency": "USD",
    "clearingExchangeRate": 1.0,
    "mcc": "5814",
    "mccGroup": "RESTAURANTS",
    "mccDescription": "FAST FOOD RESTAURANTS MISCELLANEOUS STORES",
    "merchantName": "STARBUCKS 800-782-7282",
    "merchantAddress": "150 WESTCREEK BLVD.",
    "merchantCity": "800-782-7282",
    "merchantState": "ON",
    "merchantZip": "L6T5V7",
    "authedAt": "2023-02-05T19:27:36.000+0000",
    "clearedAt": "2023-02-06T08:46:44.000+0000",
    "updatedAt": "2023-02-06T10:00:13.248+0000",
    "hasAttachments": false,
    "referenceId": "365152",
    "creditCardId": "cc_66KdhnNCr0G6hJE45PV4GU",
    "parentCreditCardId": "cc_4RSlfSqmfDVAKIgYVkXRwx",
    "sentToExpensify": false,
    "sentToQuickbooks": false,
    "attachmentsCount": 0,
    "referenceFields": [],
    "creditCardDisplayName": "Take home assignment budget",
    "parentCreditCardDisplayName": "Comdata Ghost Card",
    "creditCardHasReferenceFields": true,
    "creditCardType": "DELEGATE",
    "receiptAttachments": []
};

const txn2 = {
    "id": "txn_6TFOqz1gZ5n5ugvxo3iItg",
    "cardholderId": "u_4ghf9XE19xkAF0SFuvESez",
    "cardholderName": "Sarah Sanzari",
    "cardholderEmail": "sarah@paywithextend.com",
    "recipientName": "Tan Nguyen",
    "recipientEmail": "nt7nguye@uwaterloo.ca",
    "recipientId": "u_4oKYQdyC0vV9H3vshB133z",
    "nameOnCard": "Tan Nguyen",
    "source": "VIRTUAL",
    "receiptRequired": false,
    "vcnLast4": "4061",
    "vcnDisplayName": "Tan’s take home assignment",
    "virtualCardId": "vc_17Z9YOuZ1drA6jMwZ4ys4E",
    "type": "CREDIT",
    "status": "AUTH_REVERSAL",
    "approvalCode": "367530",
    "authBillingAmountCents": 150,
    "authBillingCurrency": "USD",
    "authMerchantAmountCents": 150,
    "authMerchantCurrency": "USD",
    "authExchangeRate": 1.0,
    "clearingBillingAmountCents": 0,
    "clearingBillingCurrency": "USD",
    "clearingMerchantAmountCents": 0,
    "clearingMerchantCurrency": "USD",
    "clearingExchangeRate": 1.0,
    "mcc": "7399",
    "mccGroup": "BUSINESS",
    "mccDescription": "BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED",
    "merchantName": "GOOGLE *TEMPORARY HOLD g.co/helppay# CAN",
    "merchantAddress": "",
    "merchantCity": "",
    "merchantState": "",
    "merchantZip": "",
    "authedAt": "2023-02-05T19:40:46.000+0000",
    "updatedAt": "2023-02-05T20:00:14.754+0000",
    "hasAttachments": false,
    "referenceId": "367530",
    "creditCardId": "cc_66KdhnNCr0G6hJE45PV4GU",
    "parentCreditCardId": "cc_4RSlfSqmfDVAKIgYVkXRwx",
    "sentToExpensify": false,
    "sentToQuickbooks": false,
    "attachmentsCount": 0,
    "referenceFields": [],
    "creditCardDisplayName": "Take home assignment budget",
    "parentCreditCardDisplayName": "Comdata Ghost Card",
    "creditCardHasReferenceFields": true,
    "creditCardType": "DELEGATE",
    "receiptAttachments": []
};

const txn3 = {
    "id": "txn_1t7kAJWyEd38stx8qg3gES",
    "cardholderId": "u_4ghf9XE19xkAF0SFuvESez",
    "cardholderName": "Sarah Sanzari",
    "cardholderEmail": "sarah@paywithextend.com",
    "recipientName": "Tan Nguyen",
    "recipientEmail": "nt7nguye@uwaterloo.ca",
    "recipientId": "u_4oKYQdyC0vV9H3vshB133z",
    "nameOnCard": "Tan Nguyen",
    "source": "VIRTUAL",
    "receiptRequired": false,
    "vcnLast4": "4061",
    "vcnDisplayName": "Tan’s take home assignment",
    "virtualCardId": "vc_17Z9YOuZ1drA6jMwZ4ys4E",
    "type": "DEBIT",
    "status": "DECLINED",
    "declineReason": "Decline - DAILY AMOUNT LIMIT EXCEEDED",
    "declineReasons": [
        {
            "code": "VIRTUAL_CARD_LIMIT_EXCEEDED",
            "description": "DAILY AMOUNT LIMIT EXCEEDED"
        }
    ],
    "approvalCode": "0",
    "authBillingAmountCents": 4712,
    "authBillingCurrency": "USD",
    "authMerchantAmountCents": 4712,
    "authMerchantCurrency": "USD",
    "authExchangeRate": 1.0,
    "clearingBillingAmountCents": 0,
    "clearingBillingCurrency": "USD",
    "clearingMerchantAmountCents": 0,
    "clearingMerchantCurrency": "USD",
    "clearingExchangeRate": 1.0,
    "mcc": "5969",
    "mccGroup": "MAIL PHONE ORDER",
    "mccDescription": "DIRECT MARKETING - OTHER DIRECT MARKETERS",
    "merchantName": "AMZN Mktp CA           AMAZON.CA     WA",
    "merchantAddress": "",
    "merchantCity": "",
    "merchantState": "",
    "merchantZip": "",
    "authedAt": "2023-02-05T20:14:54.000+0000",
    "updatedAt": "2023-02-05T21:00:14.110+0000",
    "hasAttachments": false,
    "referenceId": "0",
    "creditCardId": "cc_66KdhnNCr0G6hJE45PV4GU",
    "parentCreditCardId": "cc_4RSlfSqmfDVAKIgYVkXRwx",
    "sentToExpensify": false,
    "sentToQuickbooks": false,
    "attachmentsCount": 0,
    "referenceFields": [],
    "creditCardDisplayName": "Take home assignment budget",
    "parentCreditCardDisplayName": "Comdata Ghost Card",
    "creditCardHasReferenceFields": true,
    "creditCardType": "DELEGATE",
    "receiptAttachments": []
};

const txn4 = {
    "id": "txn_AH07MnquYGb8AhhaelxRNa",
    "cardholderId": "u_4ghf9XE19xkAF0SFuvESez",
    "cardholderName": "Sarah Sanzari",
    "cardholderEmail": "sarah@paywithextend.com",
    "recipientName": "Tan Nguyen",
    "recipientEmail": "nt7nguye@uwaterloo.ca",
    "recipientId": "u_4oKYQdyC0vV9H3vshB133z",
    "nameOnCard": "Tan Nguyen",
    "source": "VIRTUAL",
    "receiptRequired": false,
    "vcnLast4": "4061",
    "vcnDisplayName": "Tan’s take home assignment",
    "virtualCardId": "vc_17Z9YOuZ1drA6jMwZ4ys4E",
    "type": "DEBIT",
    "status": "DECLINED",
    "declineReason": "Decline - DAILY AMOUNT LIMIT EXCEEDED",
    "declineReasons": [
        {
            "code": "VIRTUAL_CARD_LIMIT_EXCEEDED",
            "description": "DAILY AMOUNT LIMIT EXCEEDED"
        }
    ],
    "approvalCode": "0",
    "authBillingAmountCents": 4712,
    "authBillingCurrency": "USD",
    "authMerchantAmountCents": 4712,
    "authMerchantCurrency": "USD",
    "authExchangeRate": 1.0,
    "clearingBillingAmountCents": 0,
    "clearingBillingCurrency": "USD",
    "clearingMerchantAmountCents": 0,
    "clearingMerchantCurrency": "USD",
    "clearingExchangeRate": 1.0,
    "mcc": "5969",
    "mccGroup": "MAIL PHONE ORDER",
    "mccDescription": "DIRECT MARKETING - OTHER DIRECT MARKETERS",
    "merchantName": "AMZN Mktp CA           AMAZON.CA     WA",
    "merchantAddress": "",
    "merchantCity": "",
    "merchantState": "",
    "merchantZip": "",
    "authedAt": "2023-02-05T21:16:42.000+0000",
    "updatedAt": "2023-02-05T22:00:13.942+0000",
    "hasAttachments": false,
    "referenceId": "0",
    "creditCardId": "cc_66KdhnNCr0G6hJE45PV4GU",
    "parentCreditCardId": "cc_4RSlfSqmfDVAKIgYVkXRwx",
    "sentToExpensify": false,
    "sentToQuickbooks": false,
    "attachmentsCount": 0,
    "referenceFields": [],
    "creditCardDisplayName": "Take home assignment budget",
    "parentCreditCardDisplayName": "Comdata Ghost Card",
    "creditCardHasReferenceFields": true,
    "creditCardType": "DELEGATE",
    "receiptAttachments": []
};

const txn5 = {
    "id": "txn_AH0J5SxtiGb7qrHPzx9iKC",
    "cardholderId": "u_4ghf9XE19xkAF0SFuvESez",
    "cardholderName": "Sarah Sanzari",
    "cardholderEmail": "sarah@paywithextend.com",
    "recipientName": "Tan Nguyen",
    "recipientEmail": "nt7nguye@uwaterloo.ca",
    "recipientId": "u_4oKYQdyC0vV9H3vshB133z",
    "nameOnCard": "Tan Nguyen",
    "source": "VIRTUAL",
    "receiptRequired": false,
    "vcnLast4": "4061",
    "vcnDisplayName": "Tan’s take home assignment",
    "virtualCardId": "vc_17Z9YOuZ1drA6jMwZ4ys4E",
    "type": "DEBIT",
    "status": "DECLINED",
    "declineReason": "Decline - DAILY AMOUNT LIMIT EXCEEDED",
    "declineReasons": [
        {
            "code": "VIRTUAL_CARD_LIMIT_EXCEEDED",
            "description": "DAILY AMOUNT LIMIT EXCEEDED"
        }
    ],
    "approvalCode": "0",
    "authBillingAmountCents": 4712,
    "authBillingCurrency": "USD",
    "authMerchantAmountCents": 4712,
    "authMerchantCurrency": "USD",
    "authExchangeRate": 1.0,
    "clearingBillingAmountCents": 0,
    "clearingBillingCurrency": "USD",
    "clearingMerchantAmountCents": 0,
    "clearingMerchantCurrency": "USD",
    "clearingExchangeRate": 1.0,
    "mcc": "5969",
    "mccGroup": "MAIL PHONE ORDER",
    "mccDescription": "DIRECT MARKETING - OTHER DIRECT MARKETERS",
    "merchantName": "AMZN Mktp CA           AMAZON.CA     WA",
    "merchantAddress": "",
    "merchantCity": "",
    "merchantState": "",
    "merchantZip": "",
    "authedAt": "2023-02-05T21:23:14.000+0000",
    "updatedAt": "2023-02-05T22:00:13.943+0000",
    "hasAttachments": false,
    "referenceId": "0",
    "creditCardId": "cc_66KdhnNCr0G6hJE45PV4GU",
    "parentCreditCardId": "cc_4RSlfSqmfDVAKIgYVkXRwx",
    "sentToExpensify": false,
    "sentToQuickbooks": false,
    "attachmentsCount": 0,
    "referenceFields": [],
    "creditCardDisplayName": "Take home assignment budget",
    "parentCreditCardDisplayName": "Comdata Ghost Card",
    "creditCardHasReferenceFields": true,
    "creditCardType": "DELEGATE",
    "receiptAttachments": []
};

const txn6 = {
    "id": "txn_AH0HRNxorZV9QNnTmFOfbx",
    "cardholderId": "u_4ghf9XE19xkAF0SFuvESez",
    "cardholderName": "Sarah Sanzari",
    "cardholderEmail": "sarah@paywithextend.com",
    "recipientName": "Tan Nguyen",
    "recipientEmail": "nt7nguye@uwaterloo.ca",
    "recipientId": "u_4oKYQdyC0vV9H3vshB133z",
    "nameOnCard": "Tan Nguyen",
    "source": "VIRTUAL",
    "receiptRequired": false,
    "vcnLast4": "4061",
    "vcnDisplayName": "Tan’s take home assignment",
    "virtualCardId": "vc_17Z9YOuZ1drA6jMwZ4ys4E",
    "type": "DEBIT",
    "status": "CLEARED",
    "approvalCode": "390002",
    "authBillingAmountCents": 3121,
    "authBillingCurrency": "USD",
    "authMerchantAmountCents": 3121,
    "authMerchantCurrency": "USD",
    "authExchangeRate": 1.0,
    "clearingBillingAmountCents": 3121,
    "clearingBillingCurrency": "USD",
    "clearingMerchantAmountCents": 3121,
    "clearingMerchantCurrency": "USD",
    "clearingExchangeRate": 1.0,
    "mcc": "5969",
    "mccGroup": "MAIL PHONE ORDER",
    "mccDescription": "DIRECT MARKETING - OTHER DIRECT MARKETERS",
    "merchantName": "AMZN MKTP CA*786EH7SN3",
    "merchantAddress": "440 TERRY AVE N",
    "merchantCity": "AMAZON.CA",
    "merchantState": "WA",
    "merchantZip": "98109",
    "authedAt": "2023-02-05T21:45:51.000+0000",
    "clearedAt": "2023-02-06T08:46:08.000+0000",
    "updatedAt": "2023-02-06T10:00:13.241+0000",
    "hasAttachments": false,
    "referenceId": "390002",
    "creditCardId": "cc_66KdhnNCr0G6hJE45PV4GU",
    "parentCreditCardId": "cc_4RSlfSqmfDVAKIgYVkXRwx",
    "sentToExpensify": false,
    "sentToQuickbooks": false,
    "attachmentsCount": 0,
    "referenceFields": [],
    "creditCardDisplayName": "Take home assignment budget",
    "parentCreditCardDisplayName": "Comdata Ghost Card",
    "creditCardHasReferenceFields": true,
    "creditCardType": "DELEGATE",
    "receiptAttachments": []
};

module.exports = {
    "transactions": [txn1, txn2, txn3, txn4, txn5, txn6],
};